name: Run Playwright Tests

on:
  # Manual trigger through GitHub UI
  workflow_dispatch:
  
  # Scheduled trigger (daily in the afternoon, 3 PM UTC)
  schedule:
    - cron: '0 15 * * *' # Adjust the time as needed (UTC timezone)

  # Trigger on changes to test files
  push:
    paths:
      - '**/tests/**'  # Adjust the path based on where your tests are located
      - '**/playwright-config/**' # Include any other relevant config paths
  pull_request:
    paths:
      - '**/tests/**'
      - '**/playwright-config/**'

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.48.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run your tests
        run: pytest
