name: Run Playwright Tests

on:
  # Manual trigger through GitHub UI
  workflow_dispatch:
  
  # Scheduled trigger (daily in the afternoon, 3 PM UTC)
  schedule:
    - cron: '0 15 * * *' # Adjust the time as needed (UTC timezone)

  # Trigger on changes to test files
  push:
    paths:
      - '**/tests/**'  # Adjust the path based on where your tests are located
      - '**/playwright-config/**' # Include any other relevant config paths
  pull_request:
    paths:
      - '**/tests/**'
      - '**/playwright-config/**'

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Use the version compatible with your project

    # Set up Docker
    - name: Set up Docker
      run: |
        docker --version

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install

    # Run Playwright tests in a Docker container
    - name: Run Playwright tests
      run: |
        docker build -t playwright-python-tests .
        docker run --rm playwright-python-tests
